# Generated by Django 5.0.3 on 2024-05-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textdata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('habitat', models.TextField()),
                ('figure', models.TextField()),
                ('suggestion', models.TextField()),
                ('img_path', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
